// <auto-generated />
using System;
using ComputerVision.Data2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputerVision.Data2.Migrations
{
    [DbContext(typeof(ComputerVisionContext))]
    [Migration("20181005115926_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputerVision.Data2.ImageFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CameraManufacturer");

                    b.Property<string>("CameraModel");

                    b.Property<string>("ContentType");

                    b.Property<DateTimeOffset>("DateCreated");

                    b.Property<DateTimeOffset>("DateTaken");

                    b.Property<string>("DisplayName");

                    b.Property<string>("DisplayType");

                    b.Property<string>("FileType");

                    b.Property<string>("FolderRelativeId");

                    b.Property<string>("HashString");

                    b.Property<long>("Height");

                    b.Property<bool>("IsAvailable");

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("Path");

                    b.Property<long>("Rating");

                    b.Property<string>("Title");

                    b.Property<long>("Width");

                    b.HasKey("Id");

                    b.ToTable("ImageFile");
                });
#pragma warning restore 612, 618
        }
    }
}
